### ISSUE TITLE
Community branch cannot save gold

### ISSUE THREAD

**Issue by ksnsk** [blizzless/blizzless-diiis#116]
Community branch cannot save gold.
It will be cleared after exiting the re-entry game.

BloodShard quantity is always zero.Can't get it.
Craftitem quantity is always zero.Can't get it.

**Comment by iamdroppy** [comment]
we have already fixed it, please can you confirm on the latest branch?

Fixed in https://github.com/blizzless/blizzless-diiis/commit/18b99cd67c7e49a76974f1fbdcf1be97360a2f97

**Comment by ksnsk** [comment]
After compiling the latest community branch, these problems still exist.
But,test-stable branch is ok.

**Comment by iamdroppy** [comment]
![download](https://user-images.githubusercontent.com/11469044/216433042-8f74a175-5910-4bab-ac18-1e891d6d925b.png)

The image above has been created using the `community` branch.

In order to ensure reproducibility, could you please verify the files committed locally to confirm this issue on the community build?

**Comment by ksnsk** [comment]
vs2022 compiling the latest community branch 2023-02-03
See the picture to illustrate : 

Get is 12 ,but, crafting materials is always zero.
![bug](https://user-images.githubusercontent.com/102937656/216609444-23df8367-653d-4f55-a6b6-0d317922187d.jpg)

Get is 1 ,but, bloodShard is always zero.
![b1](https://user-images.githubusercontent.com/102937656/216609723-53b7c25d-2887-4e13-8886-5d463176da16.jpg)

Exit the game and then re-enter the game  ,  gold is zero .  See the above picture , gold is 24.
![b2](https://user-images.githubusercontent.com/102937656/216610165-c768f1d2-85a8-482b-92f0-1e61cfc260fd.jpg)
Exit the game and then re-enter the game，and the gold coins are cleared.

**Comment by iamdroppy** [comment]
I am grateful for the guidance provided on how to replicate. I will be attempting and resolving any issues.

**Comment by iamdroppy** [comment]
I have implemented a `GetField<T>(...)` and `SetField(...)` on GameAccount.cs, which should be applied to the rest of the project if it performs as expected. The use of `lock` alongside a property getter that generates a new instance every time is not recommended (nor works), as it will lock the object for the thread (theoretically), but in reality it will just do an exxtra query, because it's a new object from a new session every time.

## Before:

```csharp
public DBGameAccount DBGameAccount => DBSessions.SessionGet<DBGameAccount>(PersistentID); // notice the =>, which makes it a getter. This property acts like a method.

// we had two kinds of setters patterns:

// case 1: works, but useless querying.
lock (DBGameAccount)
{
    var dbGAcc = DBGameAccount;
    dbGAcc.DBAccount = value.DBAccount;
    DBSessions.SessionUpdate(dbGAcc);
}

// case 2: dooesn't work. three queries being made to the game account. Admitedly, I have thought this to be a property but a read only field or a write-once property,
// not a property that acts like a method. Apologise, but let's not let it happen again to other contributors
lock (DBGameAccount)
{
    DBGameAccount.DBAccount = value.DBAccount;
    DBSessions.SessionUpdate(DBGameAccount);
}
```

## After:

```csharp
public ulong Gold
{
    // GetField will get the field based on predicate from the database. 
    // this case isn't inherently safer than DBGameAccount since it's one db connection being made.
    get => CurrentToon.IsHardcore ? GetField(s => s.HardcoreGold) : GetField(s => s.Gold);
    set
    {
        // this is where it gets interesting.
        // the "dbGameAccount" variable is the recently fetched DBGameAccount (the same way the property did, but now we know something is actually happening)
        // and no locks, at least,, it never worked in the past because the objects were never the same on the lock, so I believe we don't have a reason to add it.
        // PS: CURRENTLY we still have locks which queries another one to Db, which is unacceptable, but I'll keep it until tomorrow or so, to see the overall response.
        SetField(dbGameAccount =>
        {
            if (CurrentToon.IsHardcore)
                dbGameAccount.HardcoreGold = value;
            else
                dbGameAccount.Gold = value;
            // SetField will also take care of updating 
        });
    }
}
```

This wrapper will serve as a reference for use in a different class to facilitate the movement of additional tables, as long as it's accepted by the community.

```csharp
TSource GetField<TSource>(Func<DBGameAccount, TSource> execute) => DBSessions.GetField(PersistentID, execute);
void SetField(Action<DBGameAccount> execute, [CallerMemberName] string methodName = "") => DBSessions.SetField(PersistentID, execute);
```

And finally, on `DBSessions.GetField` and `DbSessions.SetField`

```csharp
// object obj = primary key

public static TResult GetField<TSource, TResult>(object obj, Func<TSource, TResult> execute)
{
    using IStatelessSession session = AccountDataBase.SessionProvider.SessionFactory.OpenStatelessSession();
    var db = session.Get<TSource>(obj);
    return execute(db);
}

public static void SetField<TSource>(object obj, Action<TSource> execute)
{
    using IStatelessSession session = AccountDataBase.SessionProvider.SessionFactory.OpenStatelessSession();
    var db = session.Get<TSource>(obj);
    execute(db);
    session.Update(db);
}
```
